// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/coffee/create": {
            "post": {
                "description": "Create coffee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coffee CRUD"
                ],
                "summary": "Create Coffee",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название кофе",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "URL-friendly идентификатор",
                        "name": "slug",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Цена кофе",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание кофе",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Цена в долларах",
                        "name": "dollar",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Цена в рублях",
                        "name": "ruble",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Изображение кофе",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Иконка флага страны происхождения",
                        "name": "flagIcon",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_coffee.Coffee"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_coffee.Coffee": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string",
                    "example": "Strong Italian coffee"
                },
                "dollar": {
                    "type": "number",
                    "example": 1
                },
                "flag_icon": {
                    "type": "string",
                    "example": "italy.png"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string",
                    "example": "espresso.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "Espresso"
                },
                "price": {
                    "type": "number",
                    "example": 4.99
                },
                "ruble": {
                    "type": "number",
                    "example": 89.5
                },
                "slug": {
                    "type": "string",
                    "example": "espresso"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.1",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "People-Base API documentation",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
